### ISSUE TITLE
Strange thing on loading

### ISSUE THREAD

**Issue by nitatemic** [nitatemic/AlexandreDeLemeny-Makedone_3_12042021#8]
![chrome](https://user-images.githubusercontent.com/13944652/116329433-a26a3080-a7cb-11eb-8b14-918e17a1d4dc.gif)
The loading of the site on a browser based on chromium. This is the expected behavior

![Firefox](https://user-images.githubusercontent.com/13944652/116329595-ff65e680-a7cb-11eb-95bd-63c301e13ee8.gif)
Loading the site on firefox

![safari](https://user-images.githubusercontent.com/13944652/116329827-726f5d00-a7cc-11eb-90d2-2b2ff22f0cdb.gif)
Loading the site on safari. Here it is a firework of bug.

**Comment by lemenyalex** [comment]
I use "opacity: 0%;" and "opacity: 100%" to fix the issue but, sometimes a bug appears on Safari. But now it work on Firefox
